06_WebApp_RazoePage.RazorPage/Pages/Default/Index.cshtml.cs
using _06_WebApp_RazoePage.RazorPage.Pages.BasePage;
using _06_WebApp_RazoePage.RazorPage.Pages.Movies;
using _06_WebApp_RazoePage.RazorPage.ViewModels.Moveis;
using _06_WebApp_RazoePage.WebApi.DtoModels.Movies;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace _06_WebApp_RazoePage.RazorPage.Pages.Default
{
	public class IndexModel : BaseMovieFetchPageModel
	{
		public IndexModel(
			IHttpClientFactory httpClientFactory, 
			ILogger<BaseRazorPage<MovieItemDtoModel, MovieItemViewModel>> logger, 
			IMapper mapper,
			IMemoryCache memoryCache) 
			: base(httpClientFactory, logger, mapper, memoryCache)
		{
		}

		public string MovieCoverImageUri => "https://localhost:7249";

		public async Task<IActionResult> OnGetAsync()
		{
			await GetMoviesItemListAsync("فیلمی ثبت نشده است");
			return MovieThumbnailItemList is not null ? Page() : RedirectToPage("/Error/Index");
		}

	}
}

06_WebApp_RazoePage.RazorPage/ViewComponents/MovieSidebarViewComponent.cs
using _06_WebApp_RazoePage.Data.Contracts;
using _06_WebApp_RazoePage.RazorPage.Extensions;
using _06_WebApp_RazoePage.RazorPage.ViewModels.Moveis;
using _06_WebApp_RazoePage.WebApi.Common;
using _06_WebApp_RazoePage.WebApi.DtoModels.Movies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Newtonsoft.Json;

namespace _06_WebApp_RazoePage.RazorPage.ViewComponents
{
	public class MovieSidebarViewComponent : ViewComponent
	{
		private readonly IBaseViewComponent _baseViewComponent;

		private readonly string _movieBaseUri;

		public MovieSidebarViewComponent(IBaseViewComponent baseViewComponent)
		{
			_baseViewComponent = baseViewComponent;
			_movieBaseUri = Path.Combine("https://localhost:7249", "images", "movies");
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			IEnumerable<MovieProjectViewModel> latestMoviesList = new List<MovieProjectViewModel>();

			HttpResponseMessage response = await _baseViewComponent.Client.GetAsync("api/movie/sidebarlist");
			if (!response.IsSuccessStatusCode) { 
				await _baseViewComponent.GetResponseErrorMessages<MovieItemDtoModel>(response);
				return View(latestMoviesList);
			} 

			string contentResult = await response.Content.ReadAsStringAsync();
			var appResult = JsonConvert.DeserializeObject<
				ApplicationServiceResult<IEnumerable<MovieProjectDtoModel>>>(contentResult);
			if(appResult is null)
			{
				await _baseViewComponent.SetMessage("امکان نمایش جدیدترین فیلم ها وچود ندارد", Extensions.MessageStatus.danger);
				return View(latestMoviesList);
			}

			if(appResult.IsSuccess)
			{
				latestMoviesList = _baseViewComponent.Mapper.Map<IEnumerable<MovieProjectViewModel>>(appResult.Result);
				TempData["BaseCoverImageUri"] = _movieBaseUri;
				return View(latestMoviesList);
			}

			appResult.Errors.MapToMessages(MessageStatus.danger);
			return View(latestMoviesList);
		}
	}
}

06_WebApp_RazoePage.RazorPage/Pages/Default/Index.cshtml
@page "/"
@model _06_WebApp_RazoePage.RazorPage.Pages.Default.IndexModel
@{
	ViewBag.Title = "صفحه اصلی";
	ViewBag.CssTitle = "info";
	string movieImage = string.Empty;
}
@section styles {
	<link href="~/css/movie.style.css" rel="stylesheet" />
}
<main class="row">
	<aside class="col-md-9">
		<article>
			@if (Model.MovieThumbnailItemList is not null &&
						 Model.MovieThumbnailItemList.Any())
			{
				foreach (var movie in Model.MovieThumbnailItemList)
				{
					if (!string.IsNullOrEmpty(movie.ImageName))
					{
						movieImage = $"{Model.MovieCoverImageUri}/images/movies/{movie.ImageName}";
					}
					<section class="card mt-3 mb-4">
						<div class="card-body row">
							<aside class="col-md-3">
								<img class="img-thumbnail rounded rounded-1" src="@movieImage" alt="@movie.Title" />
							</aside>
							<aside class="col-md-9">
								<h6 class="alert alert-info">@movie.Title</h6>
								<p>@movie.Description</p>
								<p class="alert alert-warning d-inline-block p-2 m-2">@movie.Score</p>
								<p class="alert alert-warning d-inline-block p-2 m-2">@movie.GenreTitle</p>
								<div class="text-start">
									<a class="btn btn-success" asp-page="/Movies/display" asp-route-id="@movie.Id">
										<i class="bi bi-play-circle"></i>
										مشاهده فیلم
									</a>
								</div>
							</aside>
						</div>
					</section>
				}
			}
		</article>
	</aside>
	<aside class="col-md-3">
		@await Component.InvokeAsync("MovieSidebar")
	</aside>
</main>